charts/risingwave/templates/serviceaccount.yaml

This PR fixes serviceAccount annotations as describe in https://github.com/risingwavelabs/helm-charts/issues/2
closes https://github.com/risingwavelabs/helm-charts/issues/2

Fix: annotations for serviceAccount are rendered as labels

---

charts/risingwave-operator/Chart.yaml
charts/risingwave-operator/crds/risingwave-operator.crds.yaml
charts/risingwave-operator/templates/clusterrole.yaml
charts/risingwave-operator/templates/clusterrolebinding.yaml
charts/risingwave-operator/templates/deployment.yaml
charts/risingwave-operator/templates/podmonitor.yaml
charts/risingwave-operator/templates/role.yaml
charts/risingwave-operator/templates/rolebinding.yaml
charts/risingwave-operator/templates/service.yaml
charts/risingwave-operator/templates/serviceaccount.yaml
charts/risingwave-operator/values.yaml
charts/risingwave/Chart.yaml
charts/risingwave/values.yaml

Besides, fix comments and annotations.
1. Use the following values to install a `PodMonitor` while installation.
```yaml
monitor:
enabled: true
```
2. `kube-rbac-proxy` is disabled by default (breaking change but should affect nothing except monitoring). Enable it with
```yaml
proxy:
enabled: true
```

feat: add PodMonitor to operator's chart, make proxy optional

---

charts/risingwave/Chart.yaml
charts/risingwave/templates/meta-sts.yaml

The bug makes the StatefulSet definition incorrect. I'll add test cases to avoid regression later this week.

fix: fix the wrong space prune

---

.github/workflows/release.yml

ci: trigger release only when Chart.yaml changes

---

.github/workflows/release.yml

To fix https://github.com/risingwavelabs/helm-charts/actions/runs/8186625154
Reference: https://github.com/helm/chart-releaser-action
I'll need to manually trigger it once after this is merged.

fix: skip uploading if tag already exists to avoid failure

---

README.md
charts/risingwave/Chart.yaml
charts/risingwave/templates/_helpers.tpl
charts/risingwave/templates/compactor-deploy.yaml
charts/risingwave/templates/compute-sts.yaml
charts/risingwave/templates/etcd-secret.yaml
charts/risingwave/templates/meta-sts.yaml
charts/risingwave/templates/minio-secret.yaml
charts/risingwave/templates/standalone/standalone-sts.yaml
charts/risingwave/templates/validation.yaml
charts/risingwave/tests/etcd_secret_test.yaml
charts/risingwave/tests/minio_secret_test.yaml
charts/risingwave/values.yaml
examples/meta-stores/external-etcd.values.yaml
examples/state-stores/azblob.values.yaml
examples/state-stores/customize-data-directory.values.yaml
examples/state-stores/eks-s3-iam.values.yaml
examples/state-stores/external-minio.values.yaml
examples/state-stores/gcs.values.yaml
examples/state-stores/hdfs.values.yaml
examples/state-stores/obs.values.yaml
examples/state-stores/oss.values.yaml
examples/state-stores/s3-compatible.values.yaml

This is a breaking change that
- Turns off `tags.etcd` and `tags.minio` by default.
- Add a new tag `tags.bundle` to enable all the bundled sub-charts.
However it still maintains the semantics compatible. That means by explicitly providing the tags one can migrate from the old charts.
It also addressed an issue when `etcd` and `minio` are both disabled by explicitly include the `bitnami/common`.

feat: optional tags

---

charts/risingwave-operator/Chart.yaml
charts/risingwave-operator/crds/risingwave-operator.crds.yaml
charts/risingwave-operator/values.yaml

CRDs have been updated. Upgrading a release won't touch CRDs according to Helm's convention. One must execute the following command manually to update:
```kubectl
kubectl apply --server-side -f https://raw.githubusercontent.com/risingwavelabs/helm-charts/risingwave-operator-0.1.14/charts/risingwave-operator/crds/risingwave-operator.crds.yaml
```

chore: bump risingwave-operator to v0.6.3

---

charts/risingwave/templates/_helpers.tpl
charts/risingwave/tests/configmap_workload_test.yaml

Correctly handle the case when `existingConfigMap` is provided. Fix #78.

fix: mount the existing config map if provided

---

charts/risingwave/templates/compute-sts.yaml
charts/risingwave/tests/compute_auto_deregistration_test.yaml
charts/risingwave/values.yaml

In addition,
- set the default `terminationGracePeriodSeconds` of compute pods to 10s to give the hook some time,
- bump the RisingWave to v1.8.0.

feat: add pre-stop hook to unregister a compute node before its pod's termination

---

charts/risingwave/Chart.yaml
charts/risingwave/values.yaml

Reverts risingwavelabs/helm-charts#87
For the same reason as https://github.com/risingwavelabs/risingwave-operator/pull/658. The version's bumped because it's non-trivial to revoke a release with helm.

Revert "chore: bump risingwave to v1.9.0, release chart 0.1.59"

---

charts/risingwave-operator/values.yaml
charts/risingwave/values.yaml

This PR updates the RisingWave configuration for helm charts to fetch the RisingWave main container image as well as the RisingWave operator container image via a Scarf endpoint. This allows RisingWave maintainers to collect basic de-identified download and adoption metrics. It does not affect where the containers are being hosted, as Scarf is only redirecting traffic back to GHCR. 
This change was suggested by the RisingWave product team in direct discussions. To test this, download RisingWave using the new endpoint (e.g. docker pull risingwave.docker.scarf.sh/risingwavelabs/risingwave) and verify that the risingwavelabs/risingwave container downloads without issue.

feat: utilize Scarf Gateway endpoint for RisingWave image and operator helm charts

---

examples/meta-stores/postgresql.values.yaml

fix: remove `currentSchema` options from postgres meta store example

---

charts/risingwave/Chart.yaml
charts/risingwave/templates/NOTES.txt
charts/risingwave/templates/hooks/post-install-create-root-user.yaml
charts/risingwave/templates/secret.yaml
charts/risingwave/tests/secret_test.yaml
charts/risingwave/values.yaml

Add a new field under the `auth` section to let the user specify a secret to provide the password for root user.

feat: support existing secret name in auth

---

charts/risingwave/Chart.yaml
charts/risingwave/templates/compute-sts.yaml
charts/risingwave/templates/meta-sts.yaml
charts/risingwave/tests/advertising_with_ip_test.yaml
charts/risingwave/values.yaml

The same feature as introduced in https://github.com/risingwavelabs/risingwave-operator/pull/682.
Release 0.1.66.

feat: support advertising with IP to bypass DNS problems

---

charts/risingwave/Chart.yaml
charts/risingwave/templates/_helpers.tpl
charts/risingwave/templates/hooks/post-install-create-databases.yaml
charts/risingwave/templates/hooks/post-install-create-root-user.yaml
charts/risingwave/templates/meta-sts.yaml
charts/risingwave/templates/metastore/postgres-secret.yaml
charts/risingwave/templates/standalone/standalone-sts.yaml
charts/risingwave/templates/validation.yaml
charts/risingwave/tests/metastore/etcd_secret_test.yaml
charts/risingwave/tests/metastore/meta-sts_env_test.yaml
charts/risingwave/tests/metastore/postgresql_secret_test.yaml
charts/risingwave/tests/statestore/statestore_validation_test.yaml
charts/risingwave/values.yaml
docs/CONFIGURATION.md

As title, two breaking changes introduced:
- `tags.bundle` won't enable `etcd` anymore
- `postgresql` will be used for specifying values of the bundled `bitnami/postgresql`, original one is renamed to `postgresqlClient`
In that, the next chart version will be `0.2.0`.
Upgrade notice:
- Change `postgresql` section to `postgresqlClient`
- If `tags.bundle=true` is set, set it to false, and then set `tags.etcd=true` and `tags.minio=true` instead

feat: support bundled PostgreSQL

---

docs/CONFIGURATION.md

Change etcd into pg in bundled option

Change etcd into pg in bundled option

---

charts/risingwave/Chart.yaml
charts/risingwave/templates/_helpers.tpl
charts/risingwave/templates/meta-sts.yaml
charts/risingwave/templates/standalone/standalone-sts.yaml
charts/risingwave/tests/metastore/meta-sts_env_test.yaml
charts/risingwave/tests/metastore/standalone-sts_env_test.yaml
charts/risingwave/values.yaml

- Add an option `metaStore. passSQLCredentialsLegacyMode` to control the behaviour. When it's set to `false` (default), the new way is adopted. Otherwise, it will follow the legacy way.
- Add an option `metaComponent. waitForMetaStore` to control whether to have an init container to wait for the PostgreSQL/MySQL to be up before starting the meta pod.

feat: support new way to pass credentials for SQL backends

---

charts/risingwave/templates/_helpers.tpl
charts/risingwave/templates/license-secret.yaml
charts/risingwave/templates/meta-sts.yaml
charts/risingwave/templates/standalone/standalone-sts.yaml
charts/risingwave/tests/license_secret_test.yaml
charts/risingwave/tests/license_standalone_test.yaml
charts/risingwave/tests/license_test.yaml
charts/risingwave/values.yaml

> [!NOTE]
> Same as what we did in https://github.com/risingwavelabs/risingwave-operator/pull/732, the environment variable used to pass the file path is `RW_LICENSE_KEY_PATH` due to [a mistake in the original PR](https://github.com/risingwavelabs/risingwave/pull/18768#discussion_r1794983086).
- Add an option `.license.passAsFile` in the values to allow explicitly enabling the feature in https://github.com/risingwavelabs/risingwave/pull/18768. 
- The PR maintains backward compatibility.
```yaml
metaStore:
sqlite:
enabled: true
stateStore:
localFs:
enabled: true
standalone:
enabled: true
license:
secret:
name: license
key: license.jwt
passAsFile: true
image:
registry: ghcr.io
repository: risingwavelabs/risingwave
tag: nightly-20241009
```
- `select rw_test_paid_tier()` returns `t` instead …

feat: support passing license as file

---

charts/risingwave/Chart.yaml
charts/risingwave/tests/license_standalone_test.yaml
charts/risingwave/tests/license_test.yaml
charts/risingwave/values.yaml

chore: turn license.passAsFile to true and mark it as deprecated

---

charts/risingwave/Chart.yaml
charts/risingwave/templates/NOTES.txt

For example, the following notes will show when a user doesn't specify the key:
```plain
IMPORTANT:
The private key for the secret store is automatically generated and stored in a Kubernetes secret. Please back up the private key by running the following command:
kubectl get secret risingwave-secret-store -o jsonpath="{.data.privateKey}" | base64 --decode
```

feat: note about backing up auto-generated secret private key

---

charts/risingwave/templates/_helpers.tpl
charts/risingwave/templates/license-secret.yaml
charts/risingwave/tests/license_secret_test.yaml
charts/risingwave/tests/license_standalone_test.yaml
charts/risingwave/tests/license_test.yaml
charts/risingwave/values.yaml

**Motivation:**
The passAsFile parameter was redundant and added unnecessary complexity. Since passing the license as a file is now the default behavior starting from RisingWave v2.2, we can safely remove this parameter.
This close #126
**Changes:**
- Removed the passAsFile parameter from charts/risingwave/values.yaml
- Set license-related configuration by default in _helpers.tpl
- Removed all tests where passAsFile was set to false
- Removed passAsFile setup from tests where it was explicitly set to true
**Tests:**
- Verified using existing tests in charts/risingwave/tests via helm unittest
- Manually verified that the license is correctly set up in the pod container when starting a RisingWave cluster using Helm

Remove parameter passAsFile from tests and values.yaml

---

charts/risingwave/Chart.yaml
charts/risingwave/templates/frontend-deploy.yaml
charts/risingwave/tests/frontend_embedded_serving_test.yaml
charts/risingwave/values.yaml

**Motivation:**
Previously, the preStop lifecycle hook for unregistering frontend workers was added even when autoDeregistration was disabled, leading to unexpected behavior. This PR ensures the preStop hook is only present when auto-deregistration is explicitly enabled.
This fix #176
**Changes:**
- Updated the Helm template (frontend-deploy.yaml) to conditionally add the preStop lifecycle hook only when frontendComponent.autoDeregistration.enabled is true.
- Enhanced values.yaml with a documented frontendComponent.autoDeregistration.enabled field (default: false).
- Improved unit tests:
- Added a test to verify the preStop hook exists when auto-deregistration is enabled.
- Added a test to verify the preStop hook does not exist when auto-deregistration is disabled.
**Tests:**
- Ran and …

fix: fix unexpected unregister-workers preStop hook issue when autoDeregistration is disabled

---

charts/risingwave/Chart.yaml
charts/risingwave/templates/compute-sts.yaml
charts/risingwave/tests/compute_resource_groups_test.yaml
charts/risingwave/values.yaml

**Feature: Compute Resource Groups for RisingWave Helm Chart**
This PR introduces support for compute resource groups in the RisingWave Helm chart, enabling users to define multiple compute StatefulSets with distinct configurations within a single deployment.
**Key Changes**
Added a new array field (`computeComponent.resourceGroups`) under computeComponent in values.yaml.
Each entry is a map with at least a unique name and optional replicas and other compute fields.
Example:
```yaml
computeComponent:
resourceGroups:
- name: group-a
replicas: 2
- name: group-b
replicas: 5
```
**Template logic in compute-sts.yaml**
1. If resourceGroups is set and non-empty, the chart renders a separate StatefulSet for each group. Each StatefulSet inherits all fields from computeComponent unless overridden …

feat: support resource group for compute nodes in RisingWave Helm Chart
